###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: vetmanager-botman-redis
      ports:
        - "6479:6379"
      volumes:
        - ./data/redis:/data
      restart: always
      command: >
        --requirepass 123456

    webserver:
      image: nginx:alpine
      container_name: vetmanager-botman-webserver
      working_dir: /application
      links:
        - php-fpm
      volumes:
          - ../:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    botman-mysql:
      image: mysql
      container_name: vetmanager-botman-mysql
      ports:
        - "8083:3306"
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: botman
        MYSQL_USER: botman
        MYSQL_PASSWORD: 123456
      restart: always
      volumes:
        - /etc/localtime:/etc/localtime:ro

    migration:
      build: phpdocker/php-fpm
      container_name: vetmanager-botman-migation
      working_dir: /application
      env_file:
        - ../.env
      volumes:
        - ../:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/migrate.sh:/migrate.sh
      links:
        - botman-mysql
      command: /bin/bash -c "chmod +x /migrate.sh; /migrate.sh; "
      environment:
        - DB_HOST=botman-mysql
        - DB_PORT=3306
        - DB_DATABASE=botman
        - DB_USERNAME=botman
        - DB_PASSWORD=123456
        - APP_KEY=base64:my8D+TGzXvuYXdEq5pCLJg==
        - API_KEY=123456
        - APP_ENV=local

    php-fpm:
      build: phpdocker/php-fpm
      container_name: vetmanager-botman-php-fpm
      working_dir: /application
      environment:
        - DB_HOST=botman-mysql
      env_file:
        - ../.env
      links:
        - botman-mysql
      volumes:
        - ../:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

